In [7]:
import numpy as np

def toy2(xval):
    f0val = xval[0][0]**2+xval[1][0]**2+xval[2][0]**2
    df0dx = 2*xval
    fval1 = ((xval.T-np.array([[5, 2, 1]]))**2).sum()-9
    fval2 = ((xval.T-np.array([[3, 4, 3]]))**2).sum()-9
    fval = np.array([[fval1,fval2]]).T
    dfdx1 = 2*(xval.T-np.array([[5, 2, 1]]))
    dfdx2 = 2*(xval.T-np.array([[3, 4, 3]]))
    dfdx = np.concatenate((dfdx1,dfdx2))
    return f0val,df0dx,fval,dfdx

xval = np.array([[1,1,1]]).T
print(xval)
print(xval.shape)
print()

f0val,df0dx,fval,dfdx = toy2(xval)
print(f0val)
print(f0val.shape)
print()
print(df0dx)
print(df0dx.shape)
print()
print(fval)
print(fval.shape)
print()
print(dfdx)
print(dfdx.shape)


[[1]
 [1]
 [1]]
(3, 1)

3
()

[[2]
 [2]
 [2]]
(3, 1)

[[8]
 [8]]
(2, 1)

[[-8 -2  0]
 [-4 -6 -4]]
(2, 3)
