In [2]:
import numpy as np
from numpy.linalg import norm
from mmapy import mma

In [3]:
def obj_fnc(x):
    return x[0][0]**2 + x[1][0]**2 + x[2][0]**2

def grad_of(x):
    return np.transpose(np.array([[2*x[0][0],2*x[1][0],2*x[2][0]]]))

def constraints(x):
    c1 = (x[0][0]-5)**2 + (x[1][0]-2)**2 + (x[2][0]-1)**2 - 9
    c2 = (x[0][0]-3)**2 + (x[1][0]-4)**2 + (x[2][0]-3)**2 - 9
    
    c = np.transpose(np.array([[c1,c2]]))
    
    return c

def grad_const(x):
    gc = np.array([[2*(x[0][0]-5),2*(x[1][0]-2),2*(x[2][0]-1)],
                   [2*(x[0][0]-3),2*(x[1][0]-4),2*(x[2][0]-3)]])
    
    return gc

m = 2
n = 3

eeen = np.ones((n,1))
eeem = np.ones((m,1))
zeron = np.zeros((n,1))
zerom = np.zeros((m,1))

x = np.transpose(np.array([[4,3,2]]))
xmin = 0.001*eeen
xmax = 5*eeen
xold1 = x.copy()
xold2 = x.copy()

low = xmin.copy()
upp = xmax.copy()

a0 = 1
a = zerom.copy()
c = 1000*eeem
d = eeem.copy()
move = 1.0 #default value

kkt_tol = 10e-9
kkt_norm = kkt_tol*10e3

maxiter = 15

f0val = obj_fnc(x)
df0dx = grad_of(x)
fval = constraints(x)
dfdx = grad_const(x)

print(x)
print(x.shape)
print(f0val)
print(f0val.shape)
print(df0dx)
print(df0dx.shape)
print(fval)
print(fval.shape)
print(dfdx)
print(dfdx.shape)

line = f'{1} {x[0]} {x[1]} {x[2]} {f0val} {fval[0]} {fval[1]}'
print(line)

i = 1
j = 1
while kkt_norm > kkt_tol and i < maxiter:
    xmma, ymma, zmma, lam, xsi, eta, mu, zet, s, low, upp = mma.mmasub(m,n,j,x,xmin,xmax,xold1,xold2,f0val,df0dx,fval,dfdx,low,upp,a0,a,c,d,move)
    
    i+=1
    j+=1
    xold2 = xold1.copy()
    xold1 = x.copy()
    x = xmma.copy()
    
    f0val = obj_fnc(x)
    df0dx = grad_of(x)
    fval = constraints(x)
    dfdx = grad_const(x)
    
    residual,kkt_norm,residual_max = mma.kktcheck(m,n,xmma,ymma,zmma,lam,xsi,eta,mu,zet,s,xmin,xmax,df0dx,fval,dfdx,a0,a,c,d)
    
    line = f'{i} {x[0]} {x[1]} {x[2]} {f0val} {fval[0]} {fval[1]}'
    print(line)

[[4]
 [3]
 [2]]
(3, 1)
29
()
[[8]
 [6]
 [4]]
(3, 1)
[[-6]
 [-6]]
(2, 1)
[[-2  2  2]
 [ 2 -2 -2]]
(2, 3)
1 [4] [3] [2] 29 [-6] [-6]
2 [2.39053217] [1.80586262] [0.99296629] 9.961765924173902 [-2.15293886] [0.21387418]
3 [2.03850001] [1.76238121] [1.24163072] 8.8031166788749 [-0.11466973] [0.02328259]
4 [2.01779209] [1.77856693] [1.23917056] 8.770328934812262 [-0.00020081] [1.75545798e-05]
5 [2.017625] [1.7793736] [1.23825221] 8.77024955043842 [7.73925983e-07] [-2.43574059e-06]
6 [2.01755425] [1.77979759] [1.23775683] 8.770246572726814 [7.75381146e-08] [-6.10849179e-07]
7 [2.01752582] [1.77996821] [1.23755761] 8.77024612981742 [-1.80794698e-07] [-1.84574333e-07]
8 [2.01751893] [1.78000961] [1.2375093] 8.770246102733246 [-2.31191128e-07] [-1.33470657e-07]
9 [2.01751858] [1.78001172] [1.23750683] 8.770246102671825 [-2.34501046e-07] [-1.31555174e-07]
10 [2.01751864] [1.78001134] [1.23750728] 8.770246102673374 [-2.34509777e-07] [-1.31552742e-07]
11 [2.01751863] [1.78001144] [1.23750716] 8.77